---
- hosts: bonneville-swarm
  connection: local
  sudo: no
  vars_files:
    - /var/lib/supercna/answerfile.yml
  vars:
    - bonneville_deploy: false
    - docker_exports:
      - "DOCKER_HOST=tcp://{{ bonneville_docker_host }}:2376"
      - "DOCKER=/tmp/bonneville/docker-linux"
    - swarm_running_file: "/tmp/swarm_{{ bonneville_docker_name }}_is_running"
    - swarm_manager_running_file: ""
  roles:
    - bonneville
