---
- hosts: kube-master
  sudo: yes
  remote_user: vmware
  vars:
    portal_net: "10.254.0.0/16"
    kube_config_dir: /etc/kubernetes
    master_address: "{{ hostvars[groups['kube-master'][0]]['ansible_eth0']['ipv4']['address'] }}"

    # doing this because we don't have them in the public repo yet.
    # just remove these 2 line once we do
    kubernetes_package: /vagrant/kubernetes-1.0.2-1.x86_64.rpm
    flannel_package: /vagrant/flannel-0.5.2-1.x86_64.rpm
  roles:
    - kubernetes_master

- hosts: kube-node
  sudo: yes
  remote_user: vmware
  vars:
    portal_net: "10.254.0.0/16"
    update_pkg_cache: no
    # send logs to the first master
    master_address: "{{ hostvars[groups['kube-master'][0]]['ansible_eth0']['ipv4']['address'] }}"
    logstash_server: "{{ master_address }}"
    logstash_port: 32768

    # lets send remote syslog to the logstash server
    remote_syslog_server: "{{ logstash_server }}"
    remote_syslog_port: "{{ logstash_port }}"

    # doing this because we don't have them in the public repo yet.
    # just remove these 2 line once we do
    kubernetes_package: /vagrant/kubernetes-1.0.2-1.x86_64.rpm
    flannel_package: /vagrant/flannel-0.5.2-1.x86_64.rpm

    kube_config_dir: /etc/kubernetes
  roles:
    - sudo
    - pip
    - photon
    - kubernetes_node

