---
- hosts: photon
  sudo: yes
  vars:
    - update_pkg_cache: "yes"
    - start_swarm: true
    - start_swarm_manager: false
    - docker_exports:
      - "DOCKER=docker"
    - swarm_running_file: "/tmp/swarm_is_running"
    - swarm_manager_running_file: "/tmp/swarm_manager_is_running"
  roles:
    - docker
