---
- hosts: photon
  sudo: yes
  vars_files:
    - /var/lib/supercna/answerfile.yml
  vars:
    - start_swarm: false
    - kill_swarm: true
    - docker_exports:
      - "DOCKER=docker"
    - swarm_running_file: "/tmp/swarm_is_running"
    - swarm_manager_running_file: "/tmp/swarm_manager_is_running"
  roles:
    - docker

- hosts: bonneville-swarm
  sudo: no
  connection: local
  vars_files:
    - /var/lib/supercna/answerfile.yml
  vars:
    - start_swarm: false
    - kill_swarm: true
    - docker_exports:
      - "DOCKER_HOST=tcp://{{ bonneville_docker_host }}:2376"
      - "DOCKER=/tmp/bonneville/docker-linux"
    - swarm_running_file: "/tmp/swarm_{{ bonneville_docker_name }}_is_running"
    - swarm_manager_running_file: ""
  roles:
    - docker
