---
- hosts: photon
  sudo: yes
  remote_user: vmware
  vars:
    update_pkg_cache: "yes"
    docker_dns_hosts:
      - photon-01.vmware.local
      - photon-02.vmware.local
  roles:
    - registrator
