---
- name: prepare vcenter for autodeploy
  hosts: vcsa
  remote_user: root
  roles:
    - autodeploy
  vars:
    - autodeploy_vcsa: true
    - autodeploy_rules: false
  vars_files:
    - /var/lib/supervio/answerfile.yml

- name: prepare autodeploy rules
  hosts: ruleshost
  roles:
    - autodeploy
  vars:
    - autodeploy_vcsa: false
    - autodeploy_rules: true
    - ansible_ssh_user: administrator
    - ansible_ssh_pass: VMware1!
    - ansible_ssh_port: 5986
    - ansible_connection: winrm
  vars_files:
    - /var/lib/supervio/answerfile.yml
