---
- name: prepare vcenter for autodeploy
  hosts: vcsa
  remote_user: root
  roles:
    - audodeploy
  vars:
    - autodeploy_vcsa: true
    - autodeploy_rules: false

#- name: prepare autodeploy rules
#  hosts: ruleshost
#  roles:
#    - audodeploy
#  vars:
#    - autodeploy_vcsa: false
#    - autodeploy_rules: true
