---
- name: prepare vcsa for ansible
  hosts: vcsa
  remote_user: root
  gather_facts: false
  roles:
    - autodeploy # [XXX] should be seperate role
  vars:
    - prepare_vcsa: true
  vars_files:
    - /var/lib/supervio/answerfile.yml

- name: prepare vcenter for autodeploy
  hosts: vcsa
  remote_user: root
  roles:
    - autodeploy
  vars:
    - autodeploy_vcsa: true
    - autodeploy_rules: false
  vars_files:
    - /var/lib/supervio/answerfile.yml

- name: prepare autodeploy rules
  hosts: ruleshost
  roles:
    - autodeploy
  vars:
    - autodeploy_vcsa: false
    - autodeploy_rules: true
  vars_files:
    - /var/lib/supervio/answerfile.yml
