---
- name: setup vcenter with nsx for vio
  hosts: local
  roles:
    - nsx
  vars:
    - nsx_deploy: false
    - nsx_config: true
  vars_files:
    - id: /var/lib/supervio/answerfile.yml

- name: deploy nsxmanager ova
  hosts: net
  remote_user: root
  roles:
    - nsx
  vars:
    - nsx_deploy: true
    - nsx_config: false
  vars_files:
    - /var/lib/supervio/answerfile.yml
