---
#- name: setup vcenter with nsx for vio
#  hosts: local
#  roles:
#    - nsx
#  vars:
#    - nsx_deploy: false
#    - nsx_config: true

- name: deploy nsxmanager ova
  hosts: net
  remote_user: root
  roles:
    - nsx
  vars:
    - nsx_deploy: true
    - nsx_config: false
